

#How to install kakfa on Rocky Linux 8

sudo su - 
dnf install epel-release -y && dnf install java-latest-openjdk -y && dnf install wget vim tar -y 
dnf update -y && reboot now

wget https://dlcdn.apache.org/kafka/3.0.0/kafka_2.13-3.0.0.tgz

tar -xf kafka_*tgz && sudo mv kafka_2.13-3.0.0/ /usr/local/kafka

sudo su -
touch /etc/systemd/system/zookeeper.service
cat <<EOF >> /etc/systemd/system/zookeeper.service
[Unit]
Description=Apache Zookeeper server
Documentation=http://zookeeper.apache.org
Requires=network.target remote-fs.target
After=network.target remote-fs.target
[Service]
Type=simple
ExecStart=/usr/bin/bash /usr/local/kafka/bin/zookeeper-server-start.sh /usr/local/kafka/config/zookeeper.properties
ExecStop=/usr/bin/bash /usr/local/kafka/bin/zookeeper-server-stop.sh
Restart=on-abnormal
[Install]
WantedBy=multi-user.target
EOF

# Install jdk change script if path (Environment="JAVA_HOME) changes 
dnf install java-11-openjdk java-11-openjdk-devel -y 

touch /etc/systemd/system/kafka.service
cat <<EOF >> /etc/systemd/system/kafka.service
[Unit]
Description=Apache Kafka Server
Documentation=http://kafka.apache.org/documentation.html
Requires=zookeeper.service
[Service]
Type=simple
Environment="JAVA_HOME=/usr/lib/jvm/jre-11-openjdk"
ExecStart=/usr/bin/bash /usr/local/kafka/bin/kafka-server-start.sh /usr/local/kafka/config/server.properties
ExecStop=/usr/bin/bash /usr/local/kafka/bin/kafka-server-stop.sh
[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload

systemctl start zookeeper
systemctl start kafka

systemctl enable zookeeper
systemctl enable kafka

systemctl status zookeeper
systemctl status kafka

# Drop Root Privs
exit && reboot now 
# Finished Installing 


# Starting first Topic 

cd /usr/local/kafka/
bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic testevent

bin/kafka-topics.sh --list --bootstrap-server localhost:9092

Kafka offers two APIs- Producer and Consumer,  for both it offers a command-line client. The producer is responsible for creating events and the Consumer uses them to display or reads the data generated by the Producer.

Open Two terminal tabs or sessions to understand the event generator and reader setup in real-time.

#On one first terminal:
bin/kafka-console-producer.sh --broker-list localhost:9092 --topic testevent

Type some text that you want to stream and display on the consumer end.

#On the other terminal make sure you are in same directory
/usr/local/kafka

Run, the below-given command along with the topic name to check the messages or generated event data in real-time:

bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic testevent --from-beginning
